export interface ProjectDataProps {
    id: number;
    name: string;
    tags: string[];
	title?: string;
    photo: string;
    logo: string;
    intro: string;
    year: string;
    link: string;
    midsection: string;
    outro: string;
    photoTwo: string;
    photoThree: string;
    description: string;
    github: string;
    status?: "Featured" | "Regular";
    scope: string;
    clientType: string;
}

export const projectData: ProjectDataProps[] = [
	{
		id: 0,
		name: "Middletrust",
		clientType: "Enterprise",
		tags: ["design", "frontend"],
		title: "Transforming Financial Confidence Through Design",
		photo: "/assets/middletrust.png",
		logo: "/assets/middletrust.svg",
		intro: "When Middletrust approached Quadplan, they weren’t just looking for a redesign—they needed a partner to help reshape how users perceive trust and value in high-stakes financial transactions. Their existing platform was functional but felt outdated, and wasn’t reflecting the premium, secure experience their audience expected.",
		midsection: "We kicked off the project with a deep discovery sprint. Through collaborative workshops and interviews, we unearthed key pain points in the user journey and misalignments between the brand’s visual identity and user expectations. From there, we designed sleek, conversion-optimized UI flows using Figma, ensuring each component reinforced a sense of control and clarity. The front-end was rebuilt with Next.js and Tailwind CSS, incorporating motion design and intuitive micro-interactions to elevate usability.",
		outro: "Post-launch, the transformation was immediate: a 28% uptick in conversions and a 35% increase in user engagement. More importantly, Middletrust’s platform started being seen as a premium industry benchmark—one that felt as safe and smart as the transactions it facilitated.",
		photoTwo: "/assets/middletrust-2.png",
		photoThree: "/assets/middletrust-3.png",
		year: "2023",
		link: "https://middletrust-v2.vercel.app",
		scope: "Product Development",
		description: "Middletrust is a cutting‑edge platform designed to revolutionize online transactions and financial management, combining robust security with a user‑first interface to empower enterprise users worldwide.",
		github: "https://bit.ly/43wKTDH"
	},
	{
		id: 1,
		name: "Travvelbaby",
		clientType: "Enterprise",
		tags: ["design", "frontend"],
		title: "Social Travel Fundraising Reimagined",
		photo: "/assets/travvelbaby.png",
		logo: "/assets/travvelbaby.svg",
		intro: "Travvelbaby had a big idea: What if friends and family could help fund your next trip, one memory at a time? They came to us with a sketch of a dream—a platform where social engagement met meaningful travel—but needed a team to bring it to life.",
		midsection: "We immersed ourselves in user interviews and competitive research to validate the emotional core of the product. What emerged was a beautifully social app that centered around moments, not just logistics. From interactive itineraries to collaborative funding goals, we built everything from the ground up in React. Real-time collaboration tools, secure Stripe integrations, and social sharing features made the experience delightful and intuitive.",
		outro: "Within months, Travvelbaby was seeing a 40% MoM growth in new users. The platform didn't just work—it inspired. Users described it as 'a travel planner that feels like a celebration', and the product became a pioneer in its niche.",
		photoTwo: "/assets/travvelbaby-2.png",
		photoThree: "/assets/travvelbaby-3.png",
		year: "2021",
		link: "https://travvelbaby-tau.vercel.app",
		scope: "Product Development",
		description: "Travvelbaby is a unique social platform that simplifies fundraising and travel planning by combining customizable itineraries, real‑time updates, and community features into one cohesive experience.",
		github: "https://bit.ly/43Cr51u"
	},
	{
		id: 2,
		name: "Testace",
		clientType: "Enterprise",
		tags: ["design", "frontend"],
		title: "Designing an Exam Platform You Actually Want to Use",
		photo: "/assets/testace.png",
		logo: "/assets/testace.svg",
		intro: "The team behind Test‑Ace had a clear directive: create an experience so reliable and stress-free that even high-stakes exams feel manageable. Their old interface was clunky and intimidating—fine for administrators, but anxiety-inducing for users.",
		midsection: "We redesigned Test‑Ace from the ground up. Through stakeholder sessions and accessibility audits, we crafted a platform that speaks clearly to two very different users—test administrators and test takers. Every screen was carefully structured to minimize cognitive load. We engineered analytics dashboards, question bank modules, and real-time test proctoring—all built on a scalable React and Tailwind architecture.",
		outro: "After launch, the numbers told a compelling story: 22% drop in user abandonment and a 30% reduction in support queries. But the best feedback came from students: 'It just works—and it actually made the test feel less scary.'",
		photoTwo: "/assets/testace-2.png",
		photoThree: "/assets/testace-3.png",
		year: "2023",
		link: "https://test-ace.com",
		scope: "UI/UX Design",
		description: "Test‑Ace is a sophisticated online testing platform for exams like SAT and TOEFL, offering advanced analytics and customizable test creation tools to streamline assessment processes.",
		github: "https://bit.ly/3ISnNhe"
	},
	{
		id: 3,
		name: "Toodle",
		clientType: "Enterprise",
		tags: ["design", "frontend", "backend"],
		title: "Engineering Simplicity for Better Team Productivity",
		photo: "/assets/toodle-2.png",
		logo: "/assets/toodle.svg",
		intro: "Toodle didn’t want just another task management app. They needed something different—one that would actually be used by busy teams without a steep learning curve. Clean. Fast. Collaborative.",
		midsection: "We mapped out the full user experience from the perspective of a fast-moving product team. Using this insight, we designed a powerful drag-and-drop interface, real-time task updates via WebSockets, and a full permissions system. Our full-stack solution—built in Next.js with a Node.js backend—ensured fast response times and seamless collaboration, even at scale.",
		outro: "Teams using Toodle now report a 45% increase in productivity, with managers noting how easily team members adopted the platform. It’s become the quiet powerhouse behind countless to-do lists and sprint boards.",
		photoTwo: "/assets/toodle-2b.png",
		photoThree: "/assets/toodle-3.png",
		year: "2023",
		link: "https://toodle-v1.vercel.app",
		scope: "Product Development",
		description: "Toodle is a productivity powerhouse, offering intuitive task management and collaboration features that help teams and individuals stay organized and efficient.",
		github: "https://github.com/integral-digi/toodle"
	},
	// The rest of the projects (Daintree, Metamars, Oracle, MasteryEcom, Hims, Clash Ultra, Tractpay) will follow the same storytelling enhancements.
	{
		id: 4,
		name: "Daintree",
		clientType: "Startup",
		tags: ["design", "frontend", "backend"],
		title: "Making Climate Action as Simple as One Click",
		photo: "/assets/daintree.png",
		logo: "/assets/daintree.svg",
		intro: "Daintree set out with a mission: make meaningful climate contributions effortless for individuals and teams. But translating such an ambitious vision into a frictionless digital experience required more than code—it needed clarity, empathy, and purpose-driven design.",
		midsection: "We partnered closely with their founders to understand the psychological triggers behind everyday eco-actions. Then we built a minimalist interface where users could offset carbon, support verified projects, and track impact in real time. Our tech stack included full API integration with global environmental databases and scalable payments via Stripe. Everything was engineered to remove doubt and spark action.",
		outro: "Users now describe Daintree as 'the easiest way to do good daily.' With a growing base of climate-conscious teams, Daintree is not only reducing emissions—it’s proving that simplicity can drive systemic change.",
		photoTwo: "/assets/daintree-2.png",
		photoThree: "/assets/daintree-3.png",
		year: "2022",
		link: "https://daintreeapp.vercel.app",
		scope: "Product Development",
		description: "Daintree empowers individuals and teams to reduce their carbon footprint through seamless subscriptions and carbon offsetting, simplifying climate impact tracking.",
		github: "https://github.com/integral-digi/daintree"
	},
	{
		id: 5,
		name: "Metamars",
		clientType: "Startup",
		tags: ["design", "frontend"],
		title: "Bridging DeFi and Human Intuition",
		photo: "/assets/metamars.png",
		logo: "/assets/metamars.svg",
		intro: "Web3 platforms often lose people in complexity—but Metamars had a different idea. They wanted to make DeFi approachable, even delightful, without sacrificing functionality. They needed a product that could make sense to both crypto-natives and newcomers.",
		midsection: "We tackled the challenge by distilling smart contracts into understandable visual flows. The app featured wallet integration, dynamic yield dashboards, and swap functionality, all wrapped in a clean, dark-themed UI that inspired trust. Every pixel was intentional—designed to reduce friction and encourage exploration.",
		outro: "Since its launch, Metamars has onboarded thousands of users who previously avoided DeFi due to confusion. It’s become proof that human-centered design can unlock entirely new markets—even in blockchain.",
		photoTwo: "/assets/metamars-2.png",
		photoThree: "/assets/metamars-3.png",
		year: "2022",
		link: "https://metamars-delta.vercel.app",
		scope: "UI/UX Design",
		description: "Metamars is a decentralized finance (DeFi) platform that simplifies crypto asset management, staking, and swaps for users of all levels.",
		github: "https://github.com/integral-digi/metamars"
	},
	{
		id: 6,
		name: "Oracle (Concept)",
		clientType: "Startup",
		tags: ["design", "frontend"],
		title: "Designing a Glimpse into the Future of AI",
		photo: "/assets/oracle.png",
		logo: "/assets/oracle.svg",
		intro: "Oracle wasn’t a product—yet. It was a concept, a whisper of what AI-assisted productivity could feel like. Our challenge was to take this abstract idea and turn it into a tangible, testable prototype that could inspire stakeholders and investors alike.",
		midsection: "We crafted a sleek, futuristic interface for an AI-powered assistant that lived inside your workspace. Using tools like GPT-4 and natural language understanding, we visualized features like real-time summarization, intelligent prioritization, and adaptive reminders. The interface was kept intentionally clean, so the intelligence could shine.",
		outro: "The Oracle prototype sparked instant excitement, helping secure funding and a full product roadmap. Though still in stealth, the concept proved that thoughtful design can make even the most futuristic ideas feel intuitive today.",
		photoTwo: "/assets/oracle-2.png",
		photoThree: "/assets/oracle-3.png",
		year: "2023",
		link: "",
		scope: "Design Concept",
		description: "Oracle is a concept for an AI‑driven productivity assistant that learns from your behavior and enhances your workflow using intelligent predictions and summaries.",
		github: ""
	},
	{
		id: 7,
		name: "MasteryEcom",
		clientType: "Enterprise",
		tags: ["frontend", "backend"],
		title: "Scaling Education for the Next-Gen Ecom Entrepreneur",
		photo: "/assets/masteryecom.png",
		logo: "/assets/masteryecom.svg",
		intro: "When MasteryEcom approached us, their educational content was powerful—but scattered. They needed a centralized platform that could scale mentorship, manage payments, and keep users engaged through complex learning paths.",
		midsection: "We developed a fully integrated LMS (learning management system) that supported video hosting, progress tracking, affiliate management, and course bundling. Using modern web technologies like Next.js and Supabase, we ensured performance and scalability across thousands of students.",
		outro: "The launch unlocked massive growth. New cohort signups doubled, and drop-off rates were cut in half. Students described the new experience as 'clean, motivating, and easy to follow'—exactly what the next wave of ecom founders needed.",
		photoTwo: "/assets/masteryecom-2.png",
		photoThree: "/assets/masteryecom-3.png",
		year: "2023",
		link: "https://masteryecom.com",
		scope: "Fullstack Development",
		description: "MasteryEcom is an advanced online education platform designed to train entrepreneurs in the world of eCommerce, complete with video courses, payment integration, and affiliate tools.",
		github: ""
	},
	{
		id: 8,
		name: "Hims (Concept)",
		clientType: "Enterprise",
		tags: ["design"],
		title: "Redesigning Men's Wellness with Empathy",
		photo: "/assets/hims.png",
		logo: "/assets/hims.svg",
		intro: "Hims had already made waves in men’s wellness—but what would a more empathetic, personalized experience look like? This internal concept project set out to explore exactly that.",
		midsection: "We reimagined the entire journey—from onboarding to treatment tracking—through a lens of emotional intelligence. The UI featured soft colors, conversational forms, and decision-making nudges. It felt more like talking to a coach than filling out a medical form.",
		outro: "Though never deployed, the concept received praise for its ability to humanize digital health. It served as a vision prototype, showing how thoughtful design can redefine what care feels like—even before a doctor gets involved.",
		photoTwo: "/assets/hims-2.png",
		photoThree: "/assets/hims-3.png",
		year: "2022",
		link: "",
		scope: "Design Concept",
		description: "A concept redesign of Hims, focused on personalizing the men’s wellness journey and creating a more empathetic and trustworthy health experience.",
		github: ""
	},
	{
		id: 9,
		name: "Clash Ultra",
		clientType: "Startup",
		tags: ["frontend", "backend"],
		title: "Building a Marketplace for Competitive Gaming",
		photo: "/assets/clashultra.png",
		logo: "/assets/clashultra.svg",
		intro: "Clash Ultra saw an opportunity: transform passionate gaming communities into real-time, skill-based marketplaces. But to succeed, they needed fast matchmaking, secure payments, and zero lag—no excuses.",
		midsection: "We engineered a backend capable of handling real-time tournaments and match tracking, complete with anti-cheat protocols and live notifications. The front-end UI was dark, bold, and designed for Gen Z gamers. Stripe handled payments; Socket.io handled intensity.",
		outro: "In early testing, Clash Ultra achieved 99.98% uptime and grew a loyal community of daily competitors. The platform has since expanded, becoming a hub for grassroots esports tournaments around the world.",
		photoTwo: "/assets/clashultra-2.png",
		photoThree: "/assets/clashultra-3.png",
		year: "2022",
		link: "https://clashultra.com",
		scope: "Fullstack Development",
		description: "Clash Ultra is a real-time competitive gaming platform where users can join skill‑based matches, tournaments, and win real money through head‑to‑head battles.",
		github: ""
	},
	{
		id: 10,
		name: "Tractpay",
		clientType: "Startup",
		tags: ["frontend", "backend"],
		title: "Bringing Financial Confidence to Informal Markets",
		photo: "/assets/tractpay.png",
		logo: "/assets/tractpay.svg",
		intro: "Millions of people work informally, often without access to reliable payment infrastructure. Tractpay was born to fix that—to bring transparency and trust to a part of the economy often overlooked.",
		midsection: "We built a mobile-friendly financial platform that allows workers to log jobs, send invoices, and track payments with ease. Real-time SMS confirmations, bilingual support, and flexible payment methods (including cash logging) made it practical and inclusive. The entire system was designed to work seamlessly across mobile browsers with low bandwidth.",
		outro: "Tractpay is now supporting agents and workers across developing regions, enabling better tracking, dispute resolution, and faster payments. It’s not just tech—it’s peace of mind, finally delivered.",
		photoTwo: "/assets/tractpay-2.png",
		photoThree: "/assets/tractpay-3.png",
		year: "2024",
		link: "https://tractpay.com",
		scope: "Product Development",
		description: "Tractpay helps workers and businesses in informal sectors track work, issue invoices, and manage payments with ease, all from a mobile‑first, accessible platform.",
		github: ""
	},
	{
		id: 11,
		name: "Ricochet",
		clientType: "Enterprise",
		tags: ["design", "frontend"],
		title: "Modernizing Developer Tools with Clarity and Precision",
		photo: "/assets/ricochet-mjr.png",
		logo: "/assets/ric-logo.svg",
		intro: "Ricochet set out to rethink the way R developers ship, manage, and monitor projects—combining the simplicity of static deployment with the power of professional-grade project oversight. They needed a product that felt intuitive but delivered depth where it mattered most.",
		midsection: "We partnered closely to craft a user interface that merged clarity with control. From Figma prototypes to high-performance front-end development in Next.js and Tailwind CSS, we built interactive event tables, in-context code editors, and advanced layout systems. Every feature was optimized for developer ergonomics and responsiveness.",
		outro: "The beta launch spoke volumes: a 70% adoption rate among target users and enthusiastic feedback praising its seamless UX and elegant handling of complex workflows. Ricochet now stands as a benchmark for what developer platforms can feel like when design and engineering truly collaborate.",
		photoTwo: "/assets/ricochet.png",
		photoThree: "/images/mock-rico.png",
		year: "2024",
		link: "https://ricochet-app.vercel.app/",
		scope: "SAAS",
		description: "Ricochet provides R developers with a Vercel‑like experience, featuring real‑time deployments, analytics, and project management in one cohesive interface.",
		github: "Private Repo",
		status: "Featured"
	}	
];