export interface ProjectDataProps {
    id: number;
    name: string;
    tags: string[];
    photo: string;
    logo: string;
    intro: string;
    year: string;
    link: string;
    midsection: string;
    outro: string;
    photoTwo: string;
    photoThree: string;
    description: string;
    github: string;
    status?: "Featured" | "Regular";
    scope: string;
    clientType: string;
}

export const projectData: ProjectDataProps[] = [
    {
        id: 0,
        name: "Middletrust",
        clientType: "Entreprise",
        tags: ["design", "frontend"],
        photo: "/assets/middletrust.png",
        logo: "/assets/middletrust.svg",
        intro: "",
        midsection: "Middletrust desired a brand refresh, and that is what they got. Both UI/UX design and frontend development were handled by me. The result was a beautiful and user-friendly app built with NextJS, and Tailwind CSS that has increased the positive perception towards the brand, and overall conversion.",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://middletrust-v2.vercel.app",
        scope: "Product Development",
        description: "Middletrust is a cutting-edge platform designed to revolutionize online transactions and financial management. With its user-friendly interface and robust security features, Middletrust ensures seamless and secure financial interactions for users worldwide.",
        github: "https://bit.ly/43wKTDH"
    },
    {
        id: 1,
        name: "Travvelbaby",
        clientType: "Entreprise",
        tags: ["design", "frontend"],
        photo: "/assets/travvelbaby.png",
        logo: "/assets/travvelbaby.svg",
        intro: "",
        midsection: "In this project, I was tasked with bringing the entire idea to life. I worked very hard to research, conceptualize, design and develop a bespoke web-app that was modern, responsive and user-friendly.",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2021",
        link: "https://travvelbaby-tau.vercel.app",
        scope: "Product Development",
        description: "Travvelbaby is a one-of-a-kind social platform, offering comprehensive fund-raising travel planning tools and resources. From itinerary customization to real-time updates, Travvelbaby simplifies the fund-raising and travel experience, making every journey fun, memorable and hassle-free.",
        github: "https://bit.ly/43Cr51u"
    },
    {
        id: 2,
        name: "Testace",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/testace.png",
        logo: "/assets/testace.svg",
        intro: "",
        midsection: "",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://test-ace.com",
        scope: "UI/UX Design",
        description: "Test-Ace is a sophisticated online testing platform designed to streamline assessment processes for international exams like SAT, TOEFL etc. With its advanced analytics and customizable test creation tools, Test-Ace empowers educators and organizations to conduct assessments with ease and accuracy.",
        github: "https://bit.ly/3ISnNhe"
    },
    {
        id: 3,
        name: "Toodle",
        tags: ["design", "frontend", "backend"],
        clientType: "Test",
        photo: "/assets/toodle-2.png",
        logo: "/assets/toodle.svg",
        intro: "",
        midsection: "",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://toodle-v1.vercel.app",
        scope: "Product Development",
        description: "Toodle is a productivity powerhouse, offering intuitive task management and collaboration features. Whether you're managing personal projects or coordinating with a team, Toodle helps you stay organized and efficient, every step of the way.",
        github: "https://github.com/integral-digi/toodle"
    },
    {
        id: 4,
        name: "Daintree",
        tags: ["design", "frontend"],
        clientType: "Test",
        photo: "/assets/daintree.png",
        logo: "/assets/daintree.svg",
        intro: "",
        midsection: "",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://daintree-shop.vercel.app",
        scope: "Product Development",
        description: "Daintree is a visually stunning online store crafted for creatives and techies. Shop the latest gadgets, and equipments from a brand that seeks to serve users where brands like Amazon falls short",
        github: "https://bit.ly/3xd2d4w"
    },
    {
        id: 5,
        name: "Metamars",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/metamars.png",
        logo: "/assets/metamars.svg",
        intro: "",
        midsection: "",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2022",
        link: "https://swap-safemarsinu.vercel.app",
        scope: "Product Development",
        description: "Metamars is an immersive virtual reality experience that transports users to the wonders of outer space. Explore distant galaxies, witness celestial phenomena, and embark on interstellar adventures with Metamars' captivating VR simulations.",
        github: ""
    },
    {
        id: 6,
        name: "Oracle",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/oracle-2.png",
        logo: "/assets/oracle.svg",
        intro: "",
        midsection: "",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://oracel-omor.vercel.app",
        scope: "Idea Validation",
        description: "Oracle is a comprehensive data analytics platform designed to unlock insights and drive informed decision-making. With its powerful analytics tools and intuitive dashboards, Oracle empowers businesses to harness the full potential of their data assets.",
        github: ""
    },
    {
        id: 7,
        name: "MasteryEcom",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/masteryecom.png",
        logo: "/assets/masteryecom.svg",
        intro: "",
        midsection: "On this project, I was contracted to design and develop a number of tools to enable prospective and successful e-commerce entrepreneurs make informed decisions based on reliable data. We made magic and built a rich and beautiful metrics calculator, and a ROAS calculator using HTML, JS and Tailwind CSS.",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://masteryecom.com/#metric",
        scope: "Product Development",
        description: "MasteryEcom is a feature-rich e-commerce solution tailored for modern businesses. From seamless checkout experiences to robust inventory management, MasteryEcom offers everything you need to build and scale your online store with confidence.",
        github: ""
    },
    {
        id: 8,
        name: "Hims",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/hims.png",
        logo: "/assets/hims.svg",
        intro: "",
        midsection: "On this project, I was contracted to design and implement a mega footer deserving of a unique brand like Hims, the footer was designed on Figma, developed with Gatsby.JS and styled components.",
        outro: "",
        photoTwo: "",
        photoThree: "",
        year: "2023",
        link: "https://hims.com/",
        scope: "Product Development",
        description: "hims.com is a leading online healthcare platform offering personalized telemedicine services and wellness products. With its user-friendly interface and comprehensive healthcare offerings, hims.com provides convenient access to medical consultations, prescriptions, and wellness solutions, promoting overall health and well-being.",
        github: ""
    },
    {
        id: 9,
        name: "Clash Ultra",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/clashultra.png",
        logo: "/assets/clashultra.svg",
        intro: " I created a bespoke landing page template specifically tailored for indie game developers, aptly named the 'Indie Game Landing Page Template'. The objective was clear: design a responsive platform resembling the sleek interfaces of popular games like Altos Adventure and FireWatch, yet with unique enhancements to cater to indie game aesthetics.",
        midsection: "Using ReactJS as the foundational framework and complementing it with Tailwind CSS for streamlined styling, I crafted a fully functional template that seamlessly adapts across both web and mobile platforms. This responsive design ensures an optimal user experience regardless of device, crucial for engaging with gamers who are passionate about indie titles and adventure genres.",
        description: "The template features a user-friendly interface that allows developers to showcase their games effectively. By omitting a backend implementation, the focus remained on delivering a robust front-end solution that meets the immediate needs of indie game developers seeking to establish a compelling online presence.",
        photoTwo: "/assets/clashultra2.png",
        photoThree: "",
        year: "2024",
        link: "https://clashultra.vercel.app/",
        scope: "Product Development",
        outro: "I'm proud of how this project turned out, not only for its technical execution but also for the positive feedback received from the client. It reinforces my commitment to combining creativity with technical expertise to deliver solutions that resonate with target audiences effectively",
        github: "Private Repo"
    },
    {
        id: 10,
        name: "Tractpay",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/tractpay-dp.png",
        logo: "/assets/logomark.svg",
        intro: "For my latest project, I created a bespoke landing page for Tractpay, a startup in the Financial tech space. They wanted a unique eyecatching and responsive landing page that reflected their goal of becoming one of the big players in the global financial ecosystem.",
        midsection: "The page was put together using Next.JS and Tailwind CSS. It has been built to be fully responsive across web and mobile platforms.",
        description: "The landing page features a number of custom-designed mockups and images illustrating key features and an enthralling dark mode to capture the imagination of users, while keeping things fairly simple.",
        photoTwo: "/assets/tractpaydark-dp.png",
        photoThree: "",
        year: "2024",
        link: "https://tractpay.vercel.app/",
        scope: "Product Development",
        outro: "I'm proud of how this project turned out, not only for its technical execution but also for the positive feedback received from the client, we are already in talks for designing and developing all necessary front pages needed for the platform. It reinforces my commitment to combining creativity with technical expertise to deliver solutions that resonate with target audiences effectively",
        github: "Private Repo"
    },
    {
        id: 11,
        name: "Ricochet",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/ricochet-mjr.png",
        logo: "/assets/ric-logo.svg",
        intro: "Ricochet is basically Vercel for R Developers and projects.",
        midsection: "This project features a well-researched and custom-built user interface built with Next JS, and Tailwind CSS with an emphasis on device responsiveness.",
        description: "Ricochet has an interactive interface, with event tables, advanced grid rows, code boxes, and everything a developer needs to managed their deployed projects.",
        photoTwo: "/assets/ricochet.png",
        photoThree: "/images/mock-rico.png",
        year: "2024",
        link: "https://ricochet-app.vercel.app/",
        scope: "SAAS",
        outro: "Working on this project was an interesting experience for me, it was a chance to heavily contribute to an idea that has the potential to grow into a Unicorn. Special thanks goes to Josiah for trusting me with this one.",
        github: "Private Repo",
        status: "Featured"
    },
    {
        id: 12,
        name: "Research AI",
        tags: ["design", "frontend"],
        clientType: "Entreprise",
        photo: "/assets/Research-AI.png",
        logo: "/assets/r-ai-logo.svg",
        intro: "For my latest project, I developed a comprehensive platform for Research AI, aiming to create an interactive and scalable frontend experience. The project combines modern technologies with a focus on user interface design and performance.",
        midsection: "The system is built using Next.js for server-side rendering and routing, while Tailwind CSS ensures a fully responsive and customizable UI. It is designed to handle complex user interactions and integrates seamlessly with other components like custom modals, infinite canvases, and PDF viewers.",
        description: "Research AI's frontend design incorporates features like real-time updates, smooth rendering of PDFs, custom navigation systems, and modular design components. The platform leverages drag-and-drop functionality, ensuring a user-friendly experience. The dark mode option, alongside custom Gantt timelines and tab navigation systems, elevates its usability.",
        photoTwo: "/assets/research-ai-2.png",
        photoThree: "",
        year: "2024",
        link: "https://research-ai-nine.vercel.app/",
        scope: "Product Development",
        outro: "This project again was an avenue for showcasing my technical depth and attention to user needs. We are already planning for further iterations, making this platform a dynamic tool for the research community. It's been an exciting journey, from design to implementation, proving once again the importance of creativity in the technical landscape.",
        github: "Private Repo"
    },  
];
